repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [ rust ]
        entry: cargo fmt --all
        pass_filenames: false
      - id: clippy
        name: clippy
        language: system
        types: [ rust ]
        entry: cargo clippy --workspace -- -D warnings
        pass_filenames: false
